//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAllotment
    {
        public int AllotmentId { get; set; }
        public int A_RoomId { get; set; }
        public long A_StudentId { get; set; }
        public bool A_Status { get; set; }
        public System.DateTime A_DateIN { get; set; }
        public Nullable<System.DateTime> A_DateOut { get; set; }
    
        public virtual dbRoom dbRoom { get; set; }
        public virtual dbStudent dbStudent { get; set; }
    }
}
