//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbLogin
    {
        public int LoginId { get; set; }
        public string LoginEmail { get; set; }
        public string LoginPass { get; set; }
        public string LoginType { get; set; }
    }
}
