//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbMenu()
        {
            this.dbFoodItems = new HashSet<dbFoodItem>();
        }
    
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> Menu_HostelId { get; set; }
        public System.DateTime Menu_StartDate { get; set; }
        public Nullable<System.DateTime> Menu_EndDate { get; set; }
        public string Menu_Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbFoodItem> dbFoodItems { get; set; }
        public virtual dbHostel dbHostel { get; set; }
    }
}
