//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbMessAttendance
    {
        public int MessAid { get; set; }
        public int MessA_RoomId { get; set; }
        public long MessA_S_CNIC { get; set; }
        public int MessA_FoodId { get; set; }
        public System.DateTime MessACurrentDate { get; set; }
        public Nullable<int> MessACount { get; set; }
    
        public virtual dbFoodItem dbFoodItem { get; set; }
        public virtual dbRoom dbRoom { get; set; }
        public virtual dbStudent dbStudent { get; set; }
    }
}
