//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbRoom()
        {
            this.dbAllotments = new HashSet<dbAllotment>();
            this.dbMessAttendances = new HashSet<dbMessAttendance>();
        }
    
        public int RoomId { get; set; }
        public Nullable<int> Room_HostelId { get; set; }
        public int RoomNO { get; set; }
        public Nullable<byte> RoomCapacity { get; set; }
        public string Details { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAllotment> dbAllotments { get; set; }
        public virtual dbHostel dbHostel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbMessAttendance> dbMessAttendances { get; set; }
    }
}
